{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* 异常Exception\n",
    "\n",
    "* 错误 Error\n",
    "  - 逻辑错误：算法写错，例如加法写成了减法\n",
    "  - 笔误：例如变量名写错，语法错误\n",
    "  - 函数或类使用错误：也属于逻辑错误   \n",
    "\n",
    "  总之，错误是可以避免的（设置代码规范，大家应该去遵守）\n",
    "\n",
    "  \n",
    "* 异常 Exception\n",
    "\n",
    "  本意就是意外的请况;这有个前提，没有出现上面的错误，也就是说程序写的没有问题，但是在某些请况下，会出现一些意外，导致程序无法正常的执行下去\n",
    "\n",
    "* 错误和异常\n",
    "\n",
    "  再高级编程语言中，一般都有错误和异常的概念，异常是可以捕获，并被处理的，但是错误是不能被捕获的\n",
    "  \n",
    "  \n",
    "一个健壮的程序(稳定压倒一切):\n",
    "  - 尽可能的避免错误\n",
    "  - 尽可能的捕获异常、处理各种异常\n",
    "  \n",
    "* 产生异常\n",
    "  - raise 语句显示的抛出异常\n",
    "  - Python解释器自己检测到异常并引发它"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "******************************\n",
      "++++++++++++++++++++++++++++++\n",
      "##############################\n",
      "catch U Out\n",
      "==============================\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python      # 别忘了写python执行路径\n",
    "# with open('test') as f:  # 异常如果不处理，会导致当前线程挂掉\n",
    "#    pass\n",
    "\n",
    "# 注解的意思是，我注明这个标识符的类型。注明是非强制的\n",
    "# x:int :int注解 变量x python3.5+    参数注解\n",
    "def foo(x: int):\n",
    "    print('+' * 30)\n",
    "    # 如果这个异常没有处理，异常就会导致程序的非正常退出\n",
    "    try:\n",
    "        print('#' * 30)\n",
    "        open('test')\n",
    "        # print(1/x)  # raise Exception('有异常了')\n",
    "        print('@' * 30)\n",
    "    except ZeroDivisionError:    # 判断try产生的异常对象是不是该类型 相当于if分支\n",
    "        # 其他语言： try: catch\n",
    "        # 异常被抓住，相当于被处理了，这个异常就被消除了\n",
    "        # 之后的代码可以正常执行\n",
    "        print('catch U zero')\n",
    "    # 1/0\n",
    "    print('-' * 30)\n",
    "\n",
    "\n",
    "try:\n",
    "    print('*' * 30)\n",
    "    foo(0)    # 如果异常不处理，最严重的后果会导致进程的非正常退出\n",
    "    print('$' * 30)\n",
    "except:    # 抓所有类型异常 缺省捕获\n",
    "    print('catch U Out')\n",
    "print('=' * 30)\n",
    "\n",
    "# y: int = 200    # 变量注解， python3.6+\n",
    "# y = 300\n",
    "# print(y)\n",
    "# y = 'abc'    # 可以么？善意的提醒，pycharm工具提供的\n",
    "# print(y)\n",
    "\n",
    "# python a.py # exit code $? shell中可以判断\n",
    "# python a.py # a.py可以没有可执行权限x\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* 上面例子， 捕获指定类型的异常\n",
    "\n",
    "Python异常的继承(python中，所有对象的基类都是object)\n",
    "\n",
    "- BaseException\n",
    "    - SystemExit\n",
    "    - KerboardInterrupt\n",
    "    - GeneratorExit\n",
    "    - Exception    # 内建异常 和 自定义异常 都应该基于Exception\n",
    "        - RuntimeError\n",
    "            - RecursionError    # 递归异常\n",
    "        - MemoryError\n",
    "        - NameError    # 找不到标识符\n",
    "        - StopIteration    # 迭代器\n",
    "        - StopAsyncIteration\n",
    "        - ArithmeticError  # 算术异常\n",
    "            - FloatingPoinError\n",
    "            - OverflowError\n",
    "            - ZeroDivisionError    # 除0异常\n",
    "        - LookupError\n",
    "            - IndexError    # 索引异常\n",
    "            - KeyError    # key找不到 都属于找东西找不到产生的异常\n",
    "        - SyntaxError    # 语法错误异常 特殊 无法捕获\n",
    "        - OSError\n",
    "            - BlockingIOError\n",
    "            - ChildProcessError\n",
    "            - ConnectionError\n",
    "                - BrokenPipeError\n",
    "                - ConnectionAbortError\n",
    "                - ConnectionRefusedError\n",
    "                - ConnectionReseError\n",
    "            - FileExistsError    # x 模式打开文件 文件已存在异常\n",
    "            - FileNotFountError  # 文件找不到异常\n",
    "            - InterruptedError\n",
    "            - IsADirectoryError\n",
    "            - NotADirectoryError\n",
    "            - PermissionError\n",
    "            - ProcessLookupError\n",
    "            - TimeoutError\n",
    "           \n",
    " * Exception是所有内建的、非系统退出的异常的基类，自定义异常类应该继承自它\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "print('+' * 30)\n",
    "sys.exit(100)\n",
    "print('+' * 30)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import time\n",
    "\n",
    "\n",
    "class MyException(Exception):\n",
    "    pass\n",
    "\n",
    "\n",
    "print('+' * 30)\n",
    "try:\n",
    "    # # sys.exit(10)    # 当前进程由此退出，会抛出一个异常\n",
    "    # while True:\n",
    "    #     time.sleep(1)\n",
    "    #     print('running ~')\n",
    "    open('test')\n",
    "    raise MyException('我自定义的异常')\n",
    "# shell ctrl+c KeyboardInterrupt\n",
    "# 其实就是判断 抛出的异常类 isinstance(except后面写的类)\n",
    "# 捕获会发生的异常类 或者 其父类 都可\n",
    "# 最大写到：Exception\n",
    "except MyException:    # 缺省捕获 不分类型，什么异常都可以捕获\n",
    "    print('有异常 Catch U')\n",
    "print('+' * 30)    # 注意退出状态码 Exit Code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MyException(Exception):\n",
    "    pass\n",
    "\n",
    "print('+' * 30)\n",
    "try:\n",
    "    # sys.exit(100)\n",
    "    # open('test')\n",
    "    print('-' * 30)\n",
    "    # raise MyException('我自定义异常')\n",
    "    print('-' * 30)\n",
    "    1/0\n",
    "\n",
    "except MyException:\n",
    "    print('My Exception')\n",
    "except ZeroDivisionError:\n",
    "    print('Zero')\n",
    "except ArithmeticError:\n",
    "    print('算术异常')\n",
    "except OSError:  # if 如果有任何一个捕获了异常，其他异常捕获分支都不会执行\n",
    "    print('OS Exception')\n",
    "except Exception:\n",
    "    print('异常+++')\n",
    "except:    # 类似 else 一定放在最后 否则语法错误\n",
    "    print('有异常')\n",
    "\n",
    "# 异常类型 没有父子关系的，顺序随便\n",
    "# 一旦有了父子类关系，子类在前(如果父类在前，后面的子类异常永远捕获不到)\n",
    "# 如果有多个捕获： 从具体异常类型 到 宽泛的异常类型\n",
    "\n",
    "print('+' * 30)  # 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* 捕获规则\n",
    "  - 捕获是从上到下一次比较 如果匹配 则执行匹配的except语句块\n",
    "  - 如果被一个except语句捕获 其他except语句就不会再次捕获\n",
    "  - 如果没有任何一个except语句捕获到这个异常，则该异常向外抛出\n",
    "  - except: 称为缺省捕获，缺省捕获必须是最后一个捕获语句\n",
    "  \n",
    "* 捕获的原则\n",
    "  - 从小到大 从具体到宽泛\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try ... except\n",
    "try ... except 类型... except\n",
    "try ... except 类型 ... except 类型 ... except 类型\n",
    "try ... except 类型 ... except 类型 ... except ...\n",
    "try ... finally\n",
    "\n",
    "try ... except 类型 ... except 类型 ... except ... finally ... "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    f = None\n",
    "    try:\n",
    "        f = open('mysql.ini')\n",
    "        print(f.read())\n",
    "        print(f.closed, '---')\n",
    "        f.write('abc')\n",
    "    finally:\n",
    "        if f:\n",
    "            f.close()   # f 可能没有定义(风险) NameError\n",
    "            print(f.closed, '+++')\n",
    "except ArithmeticError:\n",
    "    print('arith')\n",
    "except FileNotFoundError:\n",
    "    print('not found')\n",
    "except OSError as e:\n",
    "    print('os system error', e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MyException(Exception): # pass\n",
    "    def __init__(self, code):\n",
    "        self.code = 404\n",
    "\n",
    "# raise 后只能写BaseException或其子孙类的实例\n",
    "# 一般都是Exception及其子类的实例\n",
    "print('+' * 30)\n",
    "try:\n",
    "    # raise lambda x: x [] 'abc' 1\n",
    "    print('-' * 30)\n",
    "    # sys.exit(1000)\n",
    "    # raise 1\n",
    "    # raise后如果是类型 会自动调用其初始化函数\n",
    "    # 如果该类型没有初始化函数会调用其祖先类的__init__\n",
    "    # raise MyException    # 如果自定义类没有初始化方法 调用无参构造 ==> raise MyException()\n",
    "    # raise MyException('自定义异常发生')\n",
    "# except MyException:\n",
    "#     print('自定义')\n",
    "# except ZeroDivisionError:\n",
    "#     print('Zero')\n",
    "# except ArithmeticError:\n",
    "#     print('算术异常')\n",
    "# except OSError as e:  # if 如果有任何一个捕获了异常，其他异常捕获分支都不会执行\n",
    "#     print('OS Exception', e.filename)\n",
    "# except Exception as e:\n",
    "#     print('异常 +++', e, e.args, type(e))\n",
    "# except:    # 类似 else 一定放在最后 否则语法错误\n",
    "#     print('有异常 ###')\n",
    "finally:  # 最终一定会怎样，不管try中是否有异常，也不管异常是否被except捕获否\n",
    "    print('一定被执行')\n",
    "    # 一般 保证资源一定关闭\n",
    "\n",
    "print('+-' * 15)  # 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    f = None\n",
    "    try:\n",
    "        f = open('mysql.ini')\n",
    "        print(f.read())\n",
    "        print(f.closed, '---')\n",
    "        f.write('abc')\n",
    "    finally:\n",
    "        if f:\n",
    "            f.close()   # f 可能没有定义(风险) NameError\n",
    "            print(f.closed, '+++')\n",
    "except ArithmeticError:\n",
    "    print('arith')\n",
    "except FileNotFoundError:\n",
    "    print('not found')\n",
    "except OSError as e:\n",
    "    print('os system error', e)\n",
    "    raise    # 将当前异常 e 直接向外抛出;把当前激活的异常继续抛出\n",
    "    # raise e  # 抛出指定异常\n",
    "    # raise ArithmeticError  # 指定异常抛出"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
